"use strict";

// List of Spotify's top 200 tracks. Necessary since Spotify requires OAuth to access charts/popular playlists
const _TRACKS = ["One Dance",
"Too Good",
"Needed Me",
"This Is What You Came For",
"Controlla",
"Panda",
"Don't Let Me Down",
"Ride",
"Don't Mind",
'Can\'t Stop the Feeling! (Original Song from DreamWorks Animation "TROLLS")',
"Work from Home",
"Cheap Thrills",
"I Took A Pill In Ibiza - Seeb Remix",
"Broccoli",
"Treat You Better",
"Into You",
"Heathens",
"Send My Love (To Your New Lover)",
"Gold",
"Never Be Like You",
"i hate u, i love u (feat. olivia o'brien)",
"Say It (feat. Tove Lo)",
"Pop Style",
"For Free",
"Capsize",
"Low Life",
"Close",
"Light It Up (feat. Nyla & Fuse ODG) - Remix",
"Middle",
"Kill Em With Kindness",
"Never Forget You",
"We Don't Talk Anymore (feat. Selena Gomez)",
"Please Don't Go",
"No Money",
"All In My Head (Flex)",
"Once In A While",
"Work",
"Hymn For The Weekend - Seeb Remix",
"THat Part",
"Wild Things",
"Fast Car - Radio Edit",
"The Ocean",
"Jumpman",
"Sex",
"Uber Everywhere",
"Me, Myself & I",
"Wicked",
"No Problem (feat. Lil Wayne & 2 Chainz)",
"oui",
"Really Really",
"This One's For You (feat. Zara Larsson) - Official Song UEFA EURO 2016",
"Lush Life",
"Flexicution",
"Stressed Out",
"Wherever I Go",
"Still Here",
"Stay",
"Toothbrush",
"7 Years",
"If It Ain't Love",
"Let Me Hold You (Turn Me On)",
"H.O.L.Y.",
"Sit Still, Look Pretty",
"Perfect Strangers",
"Grammys",
"Final Song",
"Don't",
"Cut It (feat. Young Dolph)",
"Childs Play",
"Hype",
"Champions",
"Wake Up",
"Pity Party",
"Me Too",
"Chill Bill",
"You Was Right",
"Sucker For Pain (with Logic & Ty Dolla $ign feat. X Ambassadors)",
"Roses",
"Dangerous Woman",
"Hotline Bling",
"2 Phones",
"My House",
"Money Longer",
"Exchange",
"No Role Modelz",
"Cake By The Ocean",
"PILLOWTALK",
"With You",
"Sorry",
"Love Yourself",
"I Got the Keys",
"All The Way Up",
"Lost Boy",
"44 Bars",
"Let It Go",
"Alarm",
"Why You Always Hatin?",
"Body Say",
"Famous",
"In My Room (feat. Ty Dolla $ign & Tyga)",
"Father Stretch My Hands Pt. 1",
"Come and See Me (feat. Drake)",
"Dope Dealer",
"Feel No Ways",
"The Hills",
"You & Me",
"Look Alive",
"TorcH",
"White Iverson",
"MY PYT",
"Wrist",
"Rock Bottom",
"Can't Feel My Face",
"Waves",
"What Do You Mean?",
"Hello",
"No Broken Hearts (feat. Nicki Minaj)",
"9",
"Lean On (feat. MÃ˜ & DJ Snake)",
"Super Mario World",
"Ophelia",
"679 (feat. Remy Boyz)",
"Pick Up the Phone",
"Sorry Not Sorry",
"Fire & Desire",
"LUV",
"Trap Queen",
"The Jam",
"Summer Sixteen",
"Ride Out",
"T-Shirt",
"Bored To Death",
"Calm Down",
'Just Like Fire (From the Original Motion Picture "Alice Through The Looking Glass")',
"Die A Happy Man",
"Lord Have Mercy",
"Aloha",
"No Limit",
"Go Flex",
"YOUTH",
"Ruin",
"I Mean It",
"Faded",
"Working For It - Bonus Track",
"By Any Means",
"Stitches",
"Car Radio",
"Higher",
"You Don't Own Me",
"Somewhere On A Beach",
"Redemption",
"Groovy Tony / Eddie Kane",
"Head Over Boots",
"Juke Jam (feat. Justin Bieber & Towkio)",
"Hands To Myself",
"U With Me?",
"Friends (feat. Bon Iver)",
"What They Want",
"Unsteady",
"Where Ya At",
"Antidote",
"Thinking Out Loud",
"Make You Miss Me",
"NO",
"Lockjaw",
"Kno Ya Wrong",
"Wet Dreamz",
"Kiss It Better",
"Tear In My Heart",
"Back To Back",
"From the Ground Up",
"Acquainted",
"All The Way Up (Remix)",
"Pt. 2",
"Peter Pan",
"JoHn Muir",
"Huntin', Fishin' And Lovin' Every Day",
"American Country Love Song",
"WHateva U Want",
"Sunshine",
"F*ck Up Some Commas",
"Record Year",
"One Night - Extended",
"Promise",
'See You Again (feat. Charlie Puth) - From "Furious 7"',
"Flex (Ooh, Ooh, Ooh)",
"Photograph",
"Technically Single",
"Cheap Thrills",
"Big Rings",
"Ni**as In Paris",
"Angels (feat. Saba)",
"Wavy (feat. Joe Moses)",
"Faithful",
"Humble And Kind",
"Wasted Time",
"Tennessee Whiskey",
"Different For Girls",
"Body",
"Think of You (Duet with Cassadee Pope)"];